### ISSUE TITLE
Add an option to create members via an API

### ISSUE THREAD

**Issue by wp-insider** [wp-insider/simple-membership#13]
Need to add an API option to create users like the following:
https://www.tipsandtricks-hq.com/wordpress-membership/api-creating-a-member-account-using-http-get-or-post-447

Update user here:
https://simple-membership-plugin.com/forums/topic/creatingupdating-smwp-user-accounts-remotely/

**Comment by mbrsolution** [comment]
Hi, I believe the API option has already been developed. This ticket could be closed.

Kind regards

**Comment by wp-insider** [comment]
API now exists:

https://simple-membership-plugin.com/simple-membership-api-creating-member-account-using-http-post-request/

https://simple-membership-plugin.com/simple-membership-api-updating-member-account-using-http-post-request/
