### ISSUE TITLE
More language strings not translatable

### ISSUE THREAD

**Issue by mbrsolution** [wp-insider/simple-membership#24]
Hi, the following images illustrates the strings that are currently not translatable.

Members

![members](https://user-images.githubusercontent.com/38054628/60390276-68b83800-9b16-11e9-917b-91320cce29a8.jpg)

Membership levels

![category-protection](https://user-images.githubusercontent.com/38054628/60390285-8c7b7e00-9b16-11e9-98c9-ff44227b166c.png)
![how-to-apply-content-protection](https://user-images.githubusercontent.com/38054628/60390286-8d141480-9b16-11e9-9909-575652dc1d25.jpg)

General settings

![general-settings](https://user-images.githubusercontent.com/38054628/60390315-58ed2380-9b17-11e9-9b37-45de6a3bd24b.png)
![general-settings-2](https://user-images.githubusercontent.com/38054628/60390316-5985ba00-9b17-11e9-8a45-b43263c2cc76.png)
![general-settings-3](https://user-images.githubusercontent.com/38054628/60390317-5985ba00-9b17-11e9-9c10-2b9b26feae2b.png)

Payment settings

![payment-settings](https://user-images.githubusercontent.com/38054628/60390318-64404f00-9b17-11e9-94d3-3ea081188360.png)

Login widget

![members-login-widget](https://user-images.githubusercontent.com/38054628/60390335-b3867f80-9b17-11e9-8e77-104a0f508e23.jpg)

If you need more information, let me know.

Thank you

**Comment by erommel** [comment]
@mbrsolution , I made all the stings you mentioned available for translation.

Some of them do not require any additional actions from your side. For example, member status from Members page and Login Widget already have account status translation strings, I just made the code use those.

Regarding other strings, you cannot translate those until .pot file is regenerated.

@wp-insider, can you regenerate .pot file? It seems that it's using some custom generation script so I guess you know how to handle this.

**Comment by mbrsolution** [comment]
Thank you Alexander, I will check to see if there are any more strings that need translation.

Kind regards

**Comment by wp-insider** [comment]
This is non issue. Email me any translation related stuff for this plugin.
