### ISSUE TITLE
Avoid date_default_timezone_set() usage

### ISSUE THREAD

**Issue by erommel** [wp-insider/simple-membership#32]
WP 5.3 introduced some changes related to date handling https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

It's not recommended to use `date_default_timezone_set()` function. Also one of the customers reports this function breaks functionality of other plugins https://wordpress.org/support/topic/wordpress-5-3-incompatibility/

It's being used in two files:

1. Braintree PHP SDK:
https://github.com/wp-insider/simple-membership/blob/2b5a77cbb3fb3773c4a50a33da8589a2654bdd7d/simple-membership/lib/braintree/lib/Braintree/WebhookTestingGateway.php#L550

Since WP sets default timezone to UTC when it runs, it's safe to comment out all the lines in function except of `$timestamp = strftime('%Y-%m-%dT%TZ');`

2. https://github.com/wp-insider/simple-membership/blob/2b5a77cbb3fb3773c4a50a33da8589a2654bdd7d/simple-membership/classes/class.swpm-utils.php#L29

This is related to "Use WordPress Timezone" setting of the plugin. When this option enabled, the code sets PHP default timezone to the one set in WP general settings. And this is what breaks the functionality of other plugins.

Will investigate this to find a proper solution.

**Comment by erommel** [comment]
1. https://github.com/wp-insider/simple-membership/commit/c5e683d8fc6b8474919476998e207b745e0ea554#diff-28a06f38e9dd6ad6ed050bcfbf78df70R515-R522

I've added SwpmUtils::use_gmt() function which returns _true_ if "Use WordPress Timezone" is DISABLED and _false_ if it's ENABLED.

2. Replaced all `date()` and `time()` functions affected by timezone (where applicable) with WP's `current_time()` function, which returns either GMT time or time in WP timezone (if "Use WordPress Timezone" option enabled).
https://github.com/wp-insider/simple-membership/commit/c5e683d8fc6b8474919476998e207b745e0ea554

Note I haven't changed those functions for cookies handling and logs classes as this is not needed.

3. Addons need to be checked and converted to new way of date handling. Created new issue for that https://github.com/Arsenal21/simple-membership-addons/issues/3

@wp-insider , can you please do some tests and let me know my changes aren't breaking anything? Make sure to use date-handling branch https://github.com/wp-insider/simple-membership/tree/date-handling

**Comment by wp-insider** [comment]
This has been solved.
