### ISSUE TITLE
Add strings to custom message plugin

### ISSUE THREAD

**Issue by mbrsolution** [wp-insider/simple-membership#34]
I was wondering if it would be a good idea to add the  [swpm_mini_login] strings to the following plugin?

https://wordpress.org/plugins/simple-membership-custom-messages/

What do you think? The reason why I am asking is because of the following [forum post](https://simple-membership-plugin.com/forums/topic/edit-swpm_mini_login-widget-text/#post-19573) question.

Thank you

**Comment by wp-insider** [comment]
Good idea. Will add in the next release.

**Comment by wp-insider** [comment]
Done.
