### ISSUE TITLE
Need to timestamp changes in subscriber account

### ISSUE THREAD

**Issue by utrenkner** [wp-insider/simple-membership#36]
Is there a simple possibility to save a timestamp with every change in subscriber data (membership level, address - we use the form builder plugin)? We need to create invoices for clients and thus would like to see where changes have occurred since the last invoice.

We would even be interested in paying for a solution.

**Comment by wp-insider** [comment]
You mean like when the edit profile form is submitted? There is an action hook that gets triggered when the edit profile form is submitted:
https://simple-membership-plugin.com/simple-membership-action-hook-reference/

Look at the following two hooks from the above mentioned page:

swpm_front_end_profile_edited
swpm_front_end_profile_edited_fb

**Comment by utrenkner** [comment]
Thank you @wp-insider ! This is exactly what I needed!

I now added a timestamp saving action for
swpm_front_end_registration_complete_fb
swpm_front_end_profile_edited_fb
and also added another hook in ``SwpmMemberUtils::update_membership_level``, which uses the same function. Now the timestamp in ``wp_swpm_form_builder_custom`` is inserted/updated at registration, profile edit and change of membership level.
