### ISSUE TITLE
Custom registration email body does not have variables replaced

### ISSUE THREAD

**Issue by acicovic** [wp-insider/simple-membership#43]
Hello there,

Unless I'm missing something, custom email body using `swpm_registration_complete_email_body` and `swpm_email_registration_complete_body` will not pass by the text replacing mechanism, so any variables within them will not be replaced.

In this case, [these lines](https://github.com/wp-insider/simple-membership/blob/b21a3481adba05d69e94e5cf1be8d79bdb0efbde/simple-membership/classes/class.swpm-registration.php#L72-L75) should be moved to the top of the function in order to allow variable replacing.

Also, I do not really understand the point of [this line](https://github.com/wp-insider/simple-membership/blob/b21a3481adba05d69e94e5cf1be8d79bdb0efbde/simple-membership/classes/class.swpm-registration.php#L75) since the same result can be achieved with the `swpm_registration_complete_email_body` filter which is just above? Maybe just leave one of the two?

Thanks!

**Comment by acicovic** [comment]
Hello,

The reasoning behind what I asked for is because I want to send email in different languages to members when they are subscribed manually as mentioned [here](https://wordpress.org/support/topic/back-end-registration-password-autogeneration-and-email-notification/).

This email contains variables like {email} and {password} which are not replaced because `'swpm_registration_complete_email_body'`, `'swpm_email_registration_complete_subject'` and `'swpm_email_registration_complete_body'` (lines 72, 74, 75) are after the variable replacing code which is on line 64.

So in order to do this, currently I override `'swpm_admin_end_registration_complete_user_data'` and I use a modified version of `send_reg_email()` which will pick a different text based on the current admin language and replace the variables but this solution is less than ideal.

Do you think there could be a way to resolve this through a filter that would modify body and subject text before line 64?

Thanks!

**Comment by wp-insider** [comment]
I would want to see more request for this before making changes. You can use the following function from your custom code which can replace the merge tags:

$email_body = SwpmMiscUtils::replace_dynamic_tags( $email_body, $member_id );

If there is going to be couple of lines of additional code (that offers the same functionality) then I prefer that the couple of lines of code goes to your custom code (instead of the core plugin). If I see a number of users asking for  it in the future, I will re-evaluate and make a change.

**Comment by acicovic** [comment]
OK, thank you for your consideration 👍

**Comment by acicovic** [comment]
It is possible to make this work with 15-20 lines of code.

However I notice that this is also a problem for email sent by the `reset_password()` function in `class.swpm-front-registration.php` as the `swpm_email_password_reset_subject` and `swpm_email_password_reset_body` filters are after variable replacement.

In this case it will be probably required to re-run the sql to find the user and regenerate and save the password a second time so it can be sent within the message body.

Just noting this here for the case of completeness.
