### ISSUE TITLE
class.swpm-members.php add() function: Allow $form to be true and return without output

### ISSUE THREAD

**Issue by acicovic** [wp-insider/simple-membership#44]
Hi,

I'm referring to the code located [here](https://github.com/wp-insider/simple-membership/blob/b21a3481adba05d69e94e5cf1be8d79bdb0efbde/simple-membership/classes/class.swpm-members.php#L236-L240).

Right now, I'm forced to return a space character which is a hack to satisfy the function's flow.

This code forces to return something for output. However, the output might have been done when using the hook, because some times it's not just HTML or it can be so complicated that enclosing everything within string quotes might be a hassle.

My proposal: Allow user to return `true`, and check it with the `===` operator. So if $form === true then return. For example:

```php
$form = apply_filters( 'swpm_admin_registration_form_override', '' );
if ( $form === true ) { return; } // Added line
if ( ! empty( $form ) ) {
    echo $form;
    return;
}
```

**Comment by wp-insider** [comment]
Thank you. I have added two filters that will allow you to include your custom template file. It will go out with the next release. In the meantime, you can download a zip copy form here to use it now on your site:

https://github.com/wp-insider/simple-membership/archive/master.zip
