### ISSUE TITLE
Security issue: Privilege escalation / Account takeover issue with custom roles

### ISSUE THREAD

**Issue by acicovic** [wp-insider/simple-membership#50]
Hello there,

I have a SWPM setup with custom roles that can access it in order to manage users. Although I have set a level_0 capability to those roles, they can view and edit all users that are registered as SWPM users, including Administrators.

This means that the website can be easily taken over by changing an admin or other user's password and logging in.
Even if I override the edit form, a malicious user could probably manage to do that with a POST request.

Examining the code as well as I could, I don't think I have a way to handle this in a really secure way.

Is there anything that can be done?

Related: https://wordpress.org/support/topic/give-swpm-dashboard-access-to-custom-user-roles/

**Comment by acicovic** [comment]
Possible quick fix: for custom roles, check level_0 to level_10 capability. Users with lower capability should not be able to view/edit higher capability users in SWPM admin edit form, and not be able to update them in edit() function. Some resources on level_x can be found here:

https://stackoverflow.com/questions/9913524/translate-wordpress-user-roles-to-level-0-10
https://publishpress.com/blog/user-role-levels/

**Comment by wp-insider** [comment]
This is kind of why I don't want to touch custom roles with the core plugin. I don't have the time to check all the possible issues with it.

**Comment by acicovic** [comment]
OK.

**Comment by acicovic** [comment]
Well, we have a problem. I thought that this was happening for custom user roles, but this actually also happens for built-in user roles. So a contributor can actually change an administrator password. The built-in WP users list restricts users correctly, but SWPM allows anyone having access to its control panel to change all passwords and users.

**Comment by wp-insider** [comment]
Please give me steps that I can use to reproduce. I need to test this on a standard WP install (where nothing has been modified and there are no other plugins active) and then reproduce the issue.

**Comment by acicovic** [comment]
Thank you very much for your answer.

Maybe this is something specific to my setup, I will see if I can replicate it in a vanilla install. It will take me some time though.

I'll keep you updated.

**Comment by acicovic** [comment]
Is there some way to contact your privately about security issues?

Thanks.

**Comment by wp-insider** [comment]
Hi, You can seen the issue here and the developers will have a look at it.

**Comment by acicovic** [comment]
Hi,

Both attacks have been conducted successfully using an account with editor role, but they should be possible with a contributor or author role (depending on minimum access to WP Membership setting). They give the attacker full access to an administrator account (or any type of account for that matter).

### Attack 1

For the attack to work, attacker must know admin username and email address.

- Install WP
- Install SWPM and give access to editors (WP Membership > Settings > Advanced settings > Admin Dashboard access settings)
- Create a user with editor role (let's say editor1)
- Login with editor1
- Go to WP Membership > Members > Add New
- Add username and email equal to admin user's credentials.
- Message "This email address (email) belongs to an admin user. This email cannot be used to register a new account on this site for security reasons. Contact site admin." will appear, but account is created in the background.
- Press back browser button
- In WP Membership > Members, click edit on newly created account and change password
- The admin is now locked out and editor1 has taken access. Logout from editor1 and re-login as admin using new password


### Attack 2

For this attack no known info needed, as the attacker directly changes an admin's password from members list.

- Install WP
- Install SWPM and give access to editors (WP Membership > Settings > Advanced settings > Admin Dashboard access settings)
- Create another admin (let's say admin1)
- Go to WP Membership > Members > Add New
- Add username and email equal to admin1 user's credentials.
- Message "This email address (email) belongs to an admin user. This email cannot be used to register a new account on this site for security reasons. Contact site admin." will appear, but account is created in the background.
- Press back browser button
- Create a user with editor level (let's say editor1)
- Login with editor1
- In WP Membership > Members, editor can modify admin1 account. Click edit and change admin1 password
- admin1 is now locked out and editor1 has taken access. Logout from editor1 and re-login as admin1 using new password


### Concluding thoughts

While the bug that allows anyone to add an admin user to SWPM members is a major security flaw that must be fixed, the essence of the problem is that once a user has access on the SWPM panel they can modify any SWPM member. So just preventing only admin account creation is not a solution as it fails to address the real problem. Here are some points to consider: 

- Usually admins also need to have an SWPM Membership account, so having admins as SWPM members makes sense
- This is not an admin-only issue. All other roles (custom or built-in) can be compromised using the same technique. A contributor can use this to become an editor for example
- What if a user is added to WP Membership as a subscriber and is then promoted to admin at a later date? This has just opened a security hole
- Thus security can be achieved only by managing permissions correctly


### Quick fixes

Those are quick fixes that can make things a bit more secure while a viable solution is being worked on.

- Fix the admin addition bug
- Allow non-admins to only add subscriber level users. Admins should be allowed to add admins and other user role members
- Allow non-admins to only edit subscriber level users. This will block them from updating passwords of higher-level users


### Long term solution

SWPM needs a simple but effective capabilities system that works out of the box for built-in user roles but that will also be able to work well with custom roles. Else the plugin will always stay inherently insecure.

Those capabilities must be checked whenever:
- Adding, editing and deleting members on database level
- Loading the add, edit and view member forms. View member forms should be modified to show only members that the current user has the rights to change

This could be initially developed as an add-on but it should be merged in core.
