### ISSUE TITLE
Feature Request: Hooks before member is added, edited or deleted

### ISSUE THREAD

**Issue by acicovic** [wp-insider/simple-membership#51]
Hello,

Can we have hooks firing before a member is added, edited or deleted?

for example:
`before_member_added`
`before_member_edited`
`before_member_deleted`

This way we can check and allow or prevent the process.

Thanks!

**Comment by wp-insider** [comment]
Yep, that sounds good to me. Please tell me which file and which line (for me "before_member_added" maybe a different spot in the code than what you are thinking).

**Comment by acicovic** [comment]
Hello there,

I'll step through the code and let you know. However I think that your opinion is important since you know the codebase way better than me. 

Thank you so much for being open to introducing various hooks into SWPM.

**Comment by wp-insider** [comment]
Hi, I will close this one for now to clean things up. If you end up needing this, you can re-open.
