### ISSUE TITLE
Deleted user can remain logged in and use the website

### ISSUE THREAD

**Issue by Th0masL** [wp-insider/simple-membership#55]
Hi,

I think I've discovered a bug with deleted users.

Basically, an user that is logged on its SWPM account can keep accessing the website even if it's account has been deleted.

I guess this bug is due to the presence of the cookie, that remains in the user's browser.

I believe the problem is with the function `SwpmAuth::get_instance() -> is_logged_in`, that seems to keep returning `true` even if the user doesn't have an account anymore, as long as the cookie remains valid in the browser.

I've been trying to investigate, but I've not been able to identify exactly which part of the code is responsible for this behavior.

For information, the official WordPress function `is_user_logged_in` is detecting correctly that the user is not logged in anymore once the account got deleted. Only the SWPM `is_logged_in` function seems not detecting it correctly.

Thomas

**Comment by wp-insider** [comment]
Is this when you are deleting a record from the admin interface or when the user is deleting the account himself?

**Comment by Th0masL** [comment]
It is happening when I (the admin) delete the user from the admin interface of SWPM.

I have not tried to delete my account as an user.
