### ISSUE TITLE
[FIX] [SWPM Affiliates Manager Integration] Buyer email not forwarded to Affiliates Manager

### ISSUE THREAD

**Issue by Th0masL** [wp-insider/simple-membership#62]
Hi,

I've just realized that the email address of the buyer was not forwarded correctly to **Affiliates Manager**.

The problem was in the **SWPM Affiliate Manager Integration** plugin.

In **Affiliates Manager**, the following function support to receive the buyer email :
```
# source/Tracking/RequestTracker.php, line 68 :
public function handleCheckoutWithRefKey( $purchaseLogId, $purchaseAmount, $strRefKey, $email = '') {
```
But in the **SWPM Affiliates Manager Integration**, only the 3 first parameters were provided :

```
# affiliatemgr-simple-membership-integration.php, line 60 :
$requestTracker->handleCheckoutWithRefKey( $purchaseLogId, $purchaseAmount, $strRefKey);
```
I've improved the code, so now the email address is forwarded to **Affiliates Manager**, and we can see the buyer email in the Admin Pages > Commissions page of **Affiliates Manager**.

You can see the changes here :
https://github.com/Th0masL/affiliates-manager-simple-membership-integration/compare/fix_missing_email

Feel free to add this change to the official **SWPM Affiliate Manager Integration** plugin code.

Have a good day.

Thomas

**Comment by wp-insider** [comment]
This was added.
